@startuml
left to right direction
skinparam linetype  polyline
actor "new user" as nu
actor "authorized user" as auth
actor administrator as ad
actor editor as ed
actor referee as ref
actor author as au
actor system as sys


ad -left-|> auth
ed -left-|> auth
ref -left-|> auth
author -left-|> auth

actor "guest user" as gu
rectangle "Content Management System (CMS)" {
  usecase "request registration (FR1)" as rr
  usecase "login (FR2)" as login
  usecase "change password (FR3)" as cp
  usecase "request submission (FR4)" as submit
  usecase "save submission (FR5)" as ss
  usecase "assign referees (FR6)" as ar
  usecase "save referee (FR7)" as sr
  usecase "evaluate paper (FR8)" as ep
  usecase "make decision (FR9)" as md
  usecase "make schedule (FR10)" as ms
  usecase "edit schedule (FR11)" as es
  usecase "pay attendance (FR12)" as pay


  usecase "visit CMS web page" as v
  usecase "view assigned review tasks" as vart
  usecase "manage referee tasks" as manage
  usecase "assign referees" as ar
  usecase "accept invitation to review" as air
  usecase "send to editor" as ste
  usecase "send to author" as sta
  usecase "send schedule to author" as ssta
  usecase "send ticket to user" as st
}


'1'
nu -- rr
rr -- sys

'2'
auth -- login

'3'
cp .> login : extends
cp -= sys

'4'
au -- submit

'5'
au -- ss
ss -- sys

'6'
ed -- ar
ad -- ar

'7'
ref -- air
air .> sr : includes
sr -- sys

'8'
ref -- ep
ep .> ste : includes
ste -- sys

'9'
ed -- md
ad -- md
md .> sta : includes
sta -- sys


'10'
ms -- sys
ms .> ssta : includes

'11'
ed -- es
es -- sys

'12'
au -- pay
pay -- sys
sys -- st


auth -- v
gu -- v

@enduml
