@startuml
|ui|
start
:login;

|server|
:login;

|db|
:verify_credentials;

|ui|
:submit paper;

'|server|
'':get submission form;

|ui|
repeat :fill submission form\nauthor name\naffiliations\nauthors\norder\npaper\nscope\npaper type\nabstract\nkeywords;
:browse file;

|server|
fork
    :validate fields;
fork again
    :upload file;
end fork


repeat while (form is valid?\nfields not blank\nPDF,Word\nLaTeX,filesize<=7MB) is (no, show red error message)
-> yes;

|ui|
:submit form;

|server|
:send form to backend;

|db|
:store form in database;

|ui|
stop

@enduml
