@startuml

actor "editor/administrator" as editor
actor reviewer
participant ReviewPaper
database database as db

reviewer -> ReviewPaper : access review form
activate reviewer

activate ReviewPaper
ReviewPaper -> db : get paper
activate db
ReviewPaper <-- db : paper
reviewer <- ReviewPaper : send form
reviewer -> ReviewPaper : submit form

alt form is valid
    ReviewPaper -> db : save form/paper
    ReviewPaper <-- db : ok
    deactivate db
    ReviewPaper -> editor : send to editor
    activate editor
    deactivate editor
    reviewer <-- ReviewPaper : success
else form is invalid
     reviewer <-- ReviewPaper : show error
end
deactivate reviewer
deactivate ReviewPaper
@enduml
