@startuml

actor reviewer
participant Server
database database as db
actor "editor/administrator" as editor

reviewer -> Server : access review form
activate reviewer

activate Server
Server -> db : get paper
activate db
Server <-- db : paper
reviewer <- Server : send form
reviewer -> Server : submit form

alt form is valid
    Server -> db : save form/paper
    Server <-- db : ok
    deactivate db
    Server -> editor : send to editor
    activate editor
    deactivate editor
    reviewer <-- Server : success
else form is invalid
     reviewer <-- Server : show error
end
deactivate reviewer
deactivate Server
@enduml
