@startuml

class User {
      +email
      +username
      +login()
}

class Authentication{
      +request_login(username: string, password: string)
      +request_registration(username: string, password: string, email: string)
      +change_password(username: string, old_password: string)
}

class "Administrator/Editor" {
      +assign_referee(referee_email)
      +make_decision()
      +edit_schedule()
}

class Invitation {

}

class Referee {
      +accept_invitation()
      +evaluate_paper()
}

class DatabaseHelper {
      -db_connection
      +new_user(user)
      +verify_credentials(username, password)
      +change_password(user, old_password, new_password)
}


'remember to limit the size to 7MB'
class PaperSubmission {
      +paper_type: PaperTypes
      +file: FileObject
      +key_words
      +abstract
      +main_source

      -validate_submission()
      +save_submission()
      +submit()
}

enum PaperTypes {
     PDF
     Word
     LaTeX
}

class AuthorDetails {
      +name
      +affiliation
      +contact_information
 }

class Author {
      +request_submission(author_information: List<AuthorDetails>, paper: Paper)
      +save_submission()
}

class Schedule {
      +new()
      -send_to_authors()
}

User <|-- "Administrator/Editor"
User <|-- Referee
User <|-- Author
@enduml
